uri = "http://localhost:8001"
auth_db_connect_string = "host=localhost port=8002 user=camp dbname=camp_auth"
data_db_connect_string = "host=localhost port=8002 user=camp dbname=camp_store"
admin_uname = "admin"
admin_password = "admin"
sendgrid_uri = "http://sendgrid_mock:80/"
sendgrid_auth_string = "mock don't care"
pandoc_uri = "http://pandocker:80/"
pandoc_auth = "demo-auth"
pandoc_format = "markdown+smart"